apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  RUSTFS_ACCESS_KEY: {{ .Values.rustfs.accessKey | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.rustfs.secretKey | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  META_PASSWORD: {{ .Values.postgres.password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.rustfs.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.rustfs.secretKey | quote }}
